# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run

  # Triggers the workflow on push or pull request events but only for the main branch
on: 
  repository_dispatch:
    types:
      - GetNewAPI

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 安装依赖
      run: |
        apt-get update
        apt install --assume-yes chromium-browser
    - name: 获取api文件
      run: |
        wget https://github.com/user1121114685/Wallpaper_Engine/raw/main/getapi
        chomd 777 ./getapi
        ./getapi
